# Generated by Django 4.2.7 on 2023-11-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='Post',
            name='title',
            field=models.CharField(default='post', max_length=128),
            preserve_default=False,
        ),
    ]
