# Generated by Django 4.2.7 on 2023-11-21 13:09

import accounts.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('pdf_file', models.FileField(upload_to=accounts.models.pdf_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('subject', models.CharField(default='algebra', max_length=20)),
                ('grade', models.CharField(max_length=2)),
                ('rating', models.IntegerField()),
                ('is_valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'moderaot'), (2, 'customer')], default=2),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='material',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to=settings.AUTH_USER_MODEL),
        ),
    ]
