# Generated by Django 4.2.7 on 2024-02-18 00:57

from django.db import migrations, models


def populate_status(apps, schema_editor):
    Material = apps.get_model('accounts', 'Material')
    for material in Material.objects.all():
        if material.is_valid:
            material.status = 'verified'
        else:
            material.status = 'new'
        material.save()

def reverse_populate_status(apps, schema_editor):
    Material = apps.get_model('accounts', 'Material')
    for material in Material.objects.all():
        if material.status == 'verified':
            material.is_valid = True
        else:
            material.is_valid = False
        material.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_material_alter_user_role_delete_post_material_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
        migrations.RunPython(populate_status, reverse_code=reverse_populate_status),
        migrations.AlterField(
            model_name='material',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
