# Generated by Django 4.2.7 on 2024-02-18 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_material_status_alter_material_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='is_valid',
        ),
        migrations.CreateModel(
            name='MaterialRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejection', to='accounts.material')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user_comment', models.TextField(blank=True, null=True)),
                ('commented_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='accounts.material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_infos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('material', 'user')},
            },
        ),
    ]
