# Generated by Django 4.2.7 on 2024-02-18 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_material_is_valid_materialrejection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrejection',
            name='moderator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='material_rejections', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='materialrejection',
            unique_together={('material', 'moderator')},
        ),
    ]
