# Generated by Django 4.2.7 on 2024-02-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_materialrejection_moderator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
