# Generated by Django 4.2.7 on 2024-02-18 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_material_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='materialrejection',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='accounts.material'),
        ),
    ]
