# Generated by Django 4.2.7 on 2024-02-18 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_material_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialrejection',
            old_name='moderator',
            new_name='expert',
        ),
        migrations.AlterUniqueTogether(
            name='materialrejection',
            unique_together={('material', 'expert')},
        ),
    ]
