# Generated by Django 4.2.7 on 2024-02-18 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_moderator_materialrejection_expert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrejection',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejection', to='accounts.material'),
        ),
    ]
