# Generated by Django 4.2.7 on 2024-02-18 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_materialrejection_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrejection',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='accounts.material'),
        ),
    ]
