# Generated by Django 4.2.7 on 2024-04-08 20:21

import accounts.models
import django.core.validators
from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_teacherrequest_author_teacherrequest_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='name',
        ),
        migrations.RemoveField(
            model_name='template',
            name='name',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='name',
        ),
        migrations.AddField(
            model_name='subject',
            name='name_en',
            field=models.CharField(default='en', max_length=100, verbose_name='Name (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='name_kk',
            field=models.CharField(default='kk', max_length=100, verbose_name='Name (Kazakh)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='name_ru',
            field=models.CharField(default='ru', max_length=100, verbose_name='Name (Russian)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='name_en',
            field=models.CharField(default='en', max_length=100, verbose_name='Name (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='name_kk',
            field=models.CharField(default='kk', max_length=100, verbose_name='Name (Kazakh)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='name_ru',
            field=models.CharField(default='ru', max_length=100, verbose_name='Name (Russian)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='name_en',
            field=models.CharField(default='en', max_length=100, verbose_name='Name (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='name_kk',
            field=models.CharField(default='kk', max_length=100, verbose_name='Name (Kazakh)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='name_ru',
            field=models.CharField(default='ru', max_length=100, verbose_name='Name (Russian)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacherrequest',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='teacherrequest',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.pdf_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
